#!/bin/bash
# Función para manejar la señal SIGINT (Ctrl+C)
cleanup() {
    echo -e "\n[!] Escaneo de puertos interrumpido."
    exit 1
}

# Establecer la función de limpieza para la señal SIGINT
trap cleanup SIGINT
# Verificar que se ha proporcionado al menos un argumento
if [ $# -eq 0 ]; then
    echo "Error: Se requiere al menos un host como argumento."
    echo "Es un escaneo de puertos de una IP. Ejemplo:<192.168.1.139> <10.10.0.10>"
    exit 1
fi

hosts=("$@")

for host in "${hosts[@]}"; do
    echo -e "\n[!] Scanning ports on $host\n"
    for port in $(seq 1 10000); do
        if timeout 1 bash -c "echo ' ' > /dev/tcp/$host/$port" 2> /dev/null; then
            echo -e "\t[+] Puerto $port - OPEN" &
        fi
        echo -ne "Procesando puerto: $port\r"
    done
    wait
done

echo -e "\n\n[!] Escaneo Finalizado."
